// Web/react/iterisimoveis/src/pages/SobrePage/SobrePage.jsx
import React from "react";
import "./SobrePage.css";

function SobrePage() {
  const logoUrl =
    "https://www.iteris.com.br/Iteris.Site.Cms.Theme/img/logo.svg";
  const titulo = "Sobre a Iteris";
  const descricao =
    "Somos uma empresa de tecnologia. Mas, antes disso, somos uma empresa de gente. De gente que faz acontecer!";

  return (
    <div>
      <div className="sobre-page">
        <img src={logoUrl} alt={titulo} />
        <h1>{titulo}</h1>
        <p>{descricao}</p>
      </div>
    </div>
  );
}

export default SobrePage;

// Web/angular/iterisImoveis/src/app/components/sobre-page/sobre-page.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sobre-page',
  templateUrl: './sobre-page.component.html',
  styleUrls: ['./sobre-page.component.css']
})
export class SobrePageComponent implements OnInit {

  public logoUrl = 'https://www.iteris.com.br/Iteris.Site.Cms.Theme/img/logo.svg';
  public titulo = 'Sobre a Iteris';
  public descricao = 'Somos uma empresa de tecnologia. Mas, antes disso, somos uma empresa de gente. De gente que faz acontecer!';

  constructor() { }

  ngOnInit(): void {
  }
}

<div class="wrapper">
  <img [src]="logoUrl" >
  <h1>{{titulo}}</h1>
  <p>{{descricao}}</p>
</div>
